### Get All Entries
GET {{host}}/entries.json
Accept: */*
Content-Type: application/json

### Post Add Entry
POST {{host}}/entries.json
Accept: */*
Cache-Control: no-cache
Content-Type: Application/Json

{
  "date": "Sat Jul 19 2021",
  "text": "hola6"
}

### Delete entry
DELETE {{host}}/entries/-NlQtMMmxhEXHFrQHmhn.json

### request upload imagen by http rest api


